version: '2'
services:

  bot_app:
    build: ./Application/

    ports: 
      - 7314:7314

    stdin_open: true
    tty: true

  bot_web:
    build: ./NGINX
    ports:
      - 83:83

    volumes:
      - ./NGINX:/NGINX
    links:
      - bot_app

    depends_on:
      - bot_app